on:
  push:
    branches:
      - main
      - login-gcr.io # @note: use any development branch you would like

jobs:
  build-and-push-to-gcr:
    runs-on: ubuntu-22.04
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      # checkout code
      - uses: actions/checkout@v4

      # authenticate with GCP with workload identity provider
      - uses: 'google-github-actions/auth@v2'
        id: auth
        name: Authenticate to GCP
        with:
         project_id: 'onyx-gear-440723-s4' # update with your project ID
         workload_identity_provider: '//iam.googleapis.com/projects/283480886568/locations/global/workloadIdentityPools/github/attribute.repository/pitt-cs-1660/build-and-push-image-jay-compute' # update with your Workload Identity Pool

      # configure/login with docker
      - name: gcloud Configure Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      # setup docker buildx
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: us-central1-docker.pkg.dev/onyx-gear-440723-s4/assign3/node-demo:test

# @note: you can use regular docker commands instead of the shared action
      - name: Build and Push Without Buildx
        run: |
          docker build -t us-central1.pkg.dev/onyx-gear-440723-s4/assign3/node-demo:v1 .
          docker push us-central1.pkg.dev/onyx-gear-440723-s4/assign3/node-demo:v1
          --> us-central1.pkg.dev/onyx-gear-440723-s4/assign3/node-demo:v1 <--

