on:
  push:
    branches:
      - main
      - login-gcr.io # @note: use any development branch you would like

jobs:
  build-and-push-to-gcr:
    runs-on: ubuntu-22.04
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      # checkout code
      - uses: actions/checkout@v4

      # authenticate with GCP with workload identity provider
      - uses: 'google-github-actions/auth@v2'
        id: auth
        name: Authenticate to GCP
        with:
          project_id: 'cs1660-cloudcomputing-435323'
          workload_identity_provider: 'projects/907220770549/locations/global/workloadIdentityPools/github/providers/my-repo'

      # configure/login with docker
      - name: gcloud Configure Docker
        run: gcloud auth configure-docker us-east4.pkg.dev

      # setup docker buildx
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: us-east4-docker.pkg.dev/cs1660-cloudcomputing-435323/cloud-iam-permissions-assignment/node-demo:test

# @note: you can use regular docker commands instead of the shared action
#      - name: Build and Push Without Buildx
#        run: |
#          docker build -t us-east4.pkg.dev/cs1660-cloudcomputing-435323/cloud-iam-permissions-assignment/node-demo:test .
#          docker push us-east4.pkg.dev/cs1660-cloudcomputing-435323/cloud-iam-permissions-assignment/node-demo:test
#          --> us-central1.pkg.dev/cc-fall2024/dansc0de/node-demo:v1 <--
